application:
  APP_NAME: "Customer Churn Prediction API"
  APP_VERSION: "1.0.0"
  DEBUG: false

api:
  API_PREFIX: "/api/v1"
  HOST: "localhost"
  PORT: 8000

model:
  MODEL_REGISTRY_PATH: "model_registry"

logging:
  LOG_LEVEL: "INFO"
  LOG_FILE: "app/core/logs/app.log"
  LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

prediction:
  PREDICTION_THRESHOLD: 0.5